[build-system]
requires = [
    "setuptools>=42",
    "gym==0.17.2",
    "tensorboard==2.3.0",
    "tensorboardX==1.8",
    "matplotlib",
    "ipython==6.4.0",
    "moviepy==1.0.0",
    "pyvirtualdisplay==1.3.2",
    "torch==1.6.0",
    "opencv-python==4.4.0.42",
    "ipdb==0.13.3",
    "box2d-py",
    "ray==1.11.0",
    "tqdm"
]
build-backend = "setuptools.build_meta"